version: '3.5'
services:
  accounts_db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - "./volumes/accounts_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accounts
    networks:
      - cenoa-network
  transactions_db:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - "./volumes/transactions_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transactions
    networks:
      - cenoa-network
  history_db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: historydb
    volumes:
      - "./volumes/history_db:/data/db"
      - "./volumes/history_db_logs:/var/log/mongodb/"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    networks:
      - cenoa-network
    command: [ "--bind_ip", "0.0.0.0" ]

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
    networks:
      - cenoa-network

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
    networks:
      - cenoa-network

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cenoa-network

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    volumes:
      - "./volumes/kafka/broker-2:/var/lib/kafka/data"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cenoa-network

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    entrypoint: [ '/bin/sh', '-c' ]
    depends_on:
      - kafka-1
      - kafka-2
    networks:
      - cenoa-network
    command: |
      "
      # block until kafka is reachable
      echo -e 'Waiting for 25 seconds'
      sleep 25s &&
      kafka-topics --bootstrap-server kafka-1:9092 --list
      echo -e 'Deleting Previously Created Kafka Topics'
      kafka-topics --bootstrap-server kafka-1:9092 --topic account-event-topic --delete --if-exists
      kafka-topics --bootstrap-server kafka-1:9092 --topic deposit-event-topic --delete --if-exists
      kafka-topics --bootstrap-server kafka-1:9092 --topic withdraw-event-topic --delete --if-exists
      echo -e 'Creating New Kafka Topics'
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic account-event-topic --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic deposit-event-topic --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic withdraw-event-topic --replication-factor 1 --partitions 3
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-1:9092 --list"
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka-1
      - kafka-2
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka-1:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    networks:
      - cenoa-network
#
#  accounts_service:
#    depends_on:
#      - accounts_db
#      - kafka-1
#      - kafka-2
#    image: cenoa/account-service:latest
#    restart: on-failure
#    ports:
#      - 8001:8001
#    networks:
#      - cenoa-network

#  transaction_service:
#    depends_on:
#      - transactions_db
#      - kafka-1
#      - kafka-2
#    image: cenoa/transaction-service:latest
#    restart: on-failure
#    ports:
#      - 8002:8002
#    networks:
#      - cenoa-network
#
#  history_service:
#    depends_on:
#      - history_db
#      - kafka-1
#      - kafka-2
#    image: cenoa/history-service:latest
#    restart: on-failure
#    ports:
#      - 8003:8003
#    networks:
#      - cenoa-network
  wep_app:
    image: cenoa/web-app:latest
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - cenoa-network

networks:
  cenoa-network:
    driver: bridge
