apiVersion: apps/v1
kind: Deployment
metadata:
  name: cenoa-web-app
  namespace: cenoa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cenoa-web-app
  template:
    metadata:
      labels:
        app: cenoa-web-app
    spec:
      nodeSelector:
        role: cenoa-web-app
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - cenoa-web-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: server
          imagePullPolicy: Always
          image: cenoa/cenoa-web-app:latest
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: "100m"
              memory: 100Mi
            requests:
              cpu: "100m"
              memory: 100Mi
          env:
            - name: HTTP_BIND_ADDRESS
              value: "0.0.0.0"
            - name: HTTP_BIND_PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cenoa-web-app
  namespace: cenoa
spec:
  type: ClusterIP
  selector:
    app: cenoa-web-app
  ports:
    - port: 3000
      name: http
